export interface Storage {
  /** Save a file under `key` (e.g. `products/<uuid>.webp`) and return its public URL. */
  put(key: string, data: Buffer, contentType: string): Promise<{ url: string }>;
  /** Delete a file previously returned by `put` (unknown URLs are ignored). */
  remove(url: string): Promise<void>;
}

/** Keys are generated by us, but validate anyway: lowercase path segments only. */
export function assertSafeKey(key: string): void {
  if (!/^[a-z0-9-]+(\/[a-z0-9-]+)*\.[a-z0-9]+$/.test(key)) throw new Error(`unsafe storage key: ${key}`);
}
